### ISSUE TITLE
Use Themes as Templates

### ISSUE THREAD

**Issue by haemeulrich** [StudioMercury/digital-publishing-tools-for-wordpress#27]
I'm absolutely not a programmer (forgive me if this question is stupid). Is there a way to use WordPress Themes as templates for DPS articles?

Thank you!
Haeme

**Comment by StudioMercury** [comment]
Hi @haemeulrich,

Thanks for writing in. There are so many parameters, so many libraries and scripts that could be sent up with the template that it created too many possible outcomes where the dps article would not work or show up properly. We’ve been developing HTML articles with DPS since the beginning and on tablets and smartphones performance is key. 

The best case scenario is that you make templates for DPS where you can control what scripts and images are being loaded. If you load in a script that takes over the swipe gestures then you may find that you can’t swipe to the next article in DPS. You may also find that if you load in a script from a template that was built to work for desktop, tablet and mobile it may use older versions of scripts to work across more devices. When developing for DPS you can use the newest most efficient version of jQuery since you can control what devices an app can be installed on to.

That being said, we do have on our roadmap (after we get some big items out of the way) a feature to allow you to push a post to DPS without having to make it into an article first. This would allow you to do exactly what you are asking - however - our concerns from above will still stand. 

We still firmly believe that developing templates specifically for DPS is the best possible solution.
