### ISSUE TITLE
WordPress media player uses svg for play/pause button

### ISSUE THREAD

**Issue by TimHaslam** [StudioMercury/digital-publishing-tools-for-wordpress#36]
When using the default WordPress media player, the js loads in a controls.svg file that is a sprite for all the controls (wp-includes/js/mediaelement/controls.svg) but that folder also has a controls.png. The problem is that when the article is packaged, it uses the svg which I've read causes issues on iOS. Is there a way to fix that or have it use the png instead?

**Comment by TimHaslam** [comment]
Hey guys, any thoughts here on what might be going on?

**Comment by TimHaslam** [comment]
I found that I can add a class of 'no-svg' to the body and that will pull in the png instead of the svg, however, this still doesn't work in the app. It works great in the individual article in WordPress though. Thoughts?

**Comment by StudioMercury** [comment]
Hi Tim,

We looked into this and it’s because the image isn’t in the packaged article file. The image is referenced in the CSS. The packager doesn’t search inside the CSS for images (not yet), so you’ll need to manually add this image your self. 

During packaging, the plugin will look for all links in the HTML dom (js / css / media files / etc). It grabs all of those files referenced and packages it together with the HTML inside a .article file. At this time, we don’t go into each file and look for referenced files. Most of those dependencies are relative to that file and there are many ways elements can be linked in those files. So, we only go one level deep, anything in the root of the DOM is saved. At this time, links that are referenced inside CSS files (or JS files) will need to be added using the `dpsfa_bundle_article` filter. 
There’s an example of how to do that in the article.php example. And you will need to make sure these other references are relative to the css file.

**Comment by TimHaslam** [comment]
That worked! Thank you very much.
